name: Upload Resume

on: [push]

jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get Date
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD'
      - name: Build Resume
        run: |
          python main.py AJVResume-${{ steps.date.outputs.date }}
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "tag-${{ steps.time.outputs.time }}"
          release_name: Release ${{ steps.time.outputs.time }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Upload PDF Resume
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./AJVResume-${{ steps.time.outputs.date }}.pdf"
          asset_name: "AJVResume-${{ steps.time.outputs.date }}.pdf"
          asset_content_type: application/pdf
